version: "3.8"

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - DB_USER=reactive-flashcards
      - DB_PASSWORD=reactive-flashcards
      - DB_PORT=27017
      - DB=reactive-flashcards
      - GRADLE_USER_HOME=/box
      - SERVER_PORT=8080
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db
  db:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reactive-flashcards
      - MONGO_INITDB_ROOT_PASSWORD=reactive-flashcards
      - MONGO_INITDB_DATABASE=reactive-flashcards
    ports:
      - "27017:27017"
  box:
    image: busybox
    volumes:
      - /box

volumes:
  db:
  box: